version: '2'

services:
  server:
    build: ./server/
    command: go run .
    volumes:
      - ./server:/go/src/app
    ports:
      - "4000:4000"
  client:
    build: ./client/
    command: npm run dev
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
